import type { Question } from "./quiz-queries";

type Mock = Omit<Question, "id" | "quizNumber" | "order"> & { key: string };

const raw: Record<string, Array<Omit<Mock, "category">>> = {
  Anime: [
    { key: "an1", question: "In Naruto, what is the name of the Nine-Tailed Fox sealed inside Naruto?", choices: ["Shukaku", "Kurama", "Matatabi", "Gyuki"], correctIndex: 1 },
    { key: "an2", question: "Who is the captain of the Straw Hat Pirates in One Piece?", choices: ["Zoro", "Sanji", "Luffy", "Usopp"], correctIndex: 2 },
    { key: "an3", question: "In Attack on Titan, what is the name of Eren's Titan form?", choices: ["Colossal Titan", "Armored Titan", "Attack Titan", "Beast Titan"], correctIndex: 2 },
    { key: "an4", question: "In Death Note, what is the name of Light Yagami's Shinigami?", choices: ["Rem", "Ryuk", "Sidoh", "Gelus"], correctIndex: 1 },
    { key: "an5", question: "What is the name of the academy in My Hero Academia?", choices: ["U.A. High", "Shiketsu", "Ketsubutsu", "Seiai"], correctIndex: 0 },
    { key: "an6", question: "In Demon Slayer, what breathing style does Tanjiro primarily use?", choices: ["Flame", "Thunder", "Water", "Wind"], correctIndex: 2 },
    { key: "an7", question: "Who wrote the manga Dragon Ball?", choices: ["Eiichiro Oda", "Akira Toriyama", "Masashi Kishimoto", "Tite Kubo"], correctIndex: 1 },
    { key: "an8", question: "In Fullmetal Alchemist, what is Edward Elric's automail limb?", choices: ["Left arm", "Right leg", "Right arm and left leg", "Both legs"], correctIndex: 2 },
    { key: "an9", question: "What is the highest-grossing anime film of all time (as of 2024)?", choices: ["Spirited Away", "Your Name", "Demon Slayer: Mugen Train", "Suzume"], correctIndex: 2 },
    { key: "an10", question: "In Jujutsu Kaisen, what is Gojo's cursed technique called?", choices: ["Limitless", "Ten Shadows", "Boogie Woogie", "Idle Transfiguration"], correctIndex: 0 },
    { key: "an11", question: "In Sailor Moon, what is Usagi's cat's name?", choices: ["Artemis", "Diana", "Luna", "Chibi"], correctIndex: 2 },
    { key: "an12", question: "In One Piece, what fruit did Luffy eat?", choices: ["Mera Mera no Mi", "Gomu Gomu no Mi", "Hie Hie no Mi", "Ope Ope no Mi"], correctIndex: 1 },
    { key: "an13", question: "Who is the main protagonist of Bleach?", choices: ["Ichigo Kurosaki", "Rukia Kuchiki", "Uryu Ishida", "Renji Abarai"], correctIndex: 0 },
    { key: "an14", question: "In Cowboy Bebop, what is the name of the ship?", choices: ["Swordfish", "Bebop", "Red Dragon", "Hammerhead"], correctIndex: 1 },
    { key: "an15", question: "Which Studio Ghibli film features No-Face?", choices: ["Princess Mononoke", "Howl's Moving Castle", "Spirited Away", "Ponyo"], correctIndex: 2 },
    { key: "an16", question: "In Chainsaw Man, what is Denji's devil companion called?", choices: ["Power", "Makima", "Pochita", "Aki"], correctIndex: 2 },
    { key: "an17", question: "What color is Sasuke's Sharingan when it awakens?", choices: ["Blue", "Red", "Purple", "Yellow"], correctIndex: 1 },
    { key: "an18", question: "In Hunter x Hunter, what is Gon searching for?", choices: ["Treasure", "His father", "Revenge", "A cure"], correctIndex: 1 },
    { key: "an19", question: "Which anime features Titans that eat humans?", choices: ["Tokyo Ghoul", "Attack on Titan", "Parasyte", "Berserk"], correctIndex: 1 },
    { key: "an20", question: "In Neon Genesis Evangelion, what is Unit-01?", choices: ["A robot", "An Angel", "A bio-mechanical Eva", "A spaceship"], correctIndex: 2 },
    { key: "an21", question: "Who is L's real name in Death Note?", choices: ["Light Lawliet", "L Lawliet", "Near River", "Mihael Keehl"], correctIndex: 1 },
  ],
  Gaming: [
    { key: "gm1", question: "What is the name of the protagonist in The Legend of Zelda series?", choices: ["Zelda", "Link", "Ganon", "Sheik"], correctIndex: 1 },
    { key: "gm2", question: "Which company developed the game Elden Ring?", choices: ["CD Projekt Red", "FromSoftware", "Bethesda", "Square Enix"], correctIndex: 1 },
    { key: "gm3", question: "In Minecraft, what material is required to build a Nether Portal?", choices: ["Iron", "Diamond", "Obsidian", "Netherrack"], correctIndex: 2 },
    { key: "gm4", question: "Who is the main antagonist of Super Mario Bros?", choices: ["Wario", "Bowser", "King Boo", "Donkey Kong"], correctIndex: 1 },
    { key: "gm5", question: "What year was the original PlayStation released in North America?", choices: ["1994", "1995", "1996", "1997"], correctIndex: 1 },
    { key: "gm6", question: "In Fortnite, what is the name of the in-game currency?", choices: ["V-Bucks", "Robux", "Credits", "Gems"], correctIndex: 0 },
    { key: "gm7", question: "Which game features the character Master Chief?", choices: ["Destiny", "Halo", "Call of Duty", "Gears of War"], correctIndex: 1 },
    { key: "gm8", question: "What is the best-selling video game of all time?", choices: ["Tetris", "Minecraft", "GTA V", "Wii Sports"], correctIndex: 1 },
    { key: "gm9", question: "In The Witcher 3, what is Geralt's horse named?", choices: ["Shadowmere", "Roach", "Epona", "Agro"], correctIndex: 1 },
    { key: "gm10", question: "Which game popularized the battle royale genre?", choices: ["Fortnite", "PUBG", "Apex Legends", "H1Z1"], correctIndex: 1 },
    { key: "gm11", question: "Who is the protagonist of the God of War series?", choices: ["Atreus", "Kratos", "Zeus", "Baldur"], correctIndex: 1 },
    { key: "gm12", question: "In Overwatch, what nationality is Tracer?", choices: ["American", "British", "Australian", "Canadian"], correctIndex: 1 },
    { key: "gm13", question: "What is the name of the currency in Animal Crossing?", choices: ["Rupees", "Bells", "Coins", "Zennies"], correctIndex: 1 },
    { key: "gm14", question: "Which studio developed Half-Life?", choices: ["Id Software", "Valve", "Bungie", "Blizzard"], correctIndex: 1 },
    { key: "gm15", question: "In Pokémon Red/Blue, how many original Pokémon are there?", choices: ["150", "151", "152", "149"], correctIndex: 1 },
    { key: "gm16", question: "Who is the main character of the Metal Gear series?", choices: ["Solid Snake", "Raiden", "Big Boss", "Both Snake and Big Boss"], correctIndex: 3 },
    { key: "gm17", question: "What game features the phrase 'It's dangerous to go alone!'?", choices: ["Zelda", "Final Fantasy", "Dragon Quest", "Chrono Trigger"], correctIndex: 0 },
    { key: "gm18", question: "In Among Us, what is the traitor role called?", choices: ["Killer", "Impostor", "Traitor", "Ghost"], correctIndex: 1 },
    { key: "gm19", question: "Which game series features a hero named Cloud Strife?", choices: ["Kingdom Hearts", "Final Fantasy", "Chrono", "Xenoblade"], correctIndex: 1 },
    { key: "gm20", question: "What is the top-rated game on Metacritic (as of 2024)?", choices: ["Zelda: BOTW", "Zelda: Ocarina of Time", "GTA V", "Red Dead Redemption 2"], correctIndex: 1 },
    { key: "gm21", question: "In Stardew Valley, what is the name of your grandpa's farm town?", choices: ["Stardew Valley", "Pelican Town", "Cindersap", "Zuzu City"], correctIndex: 1 },
  ],
  "Pop Culture": [
    { key: "pc1", question: "Which social media app is known for short-form vertical videos and launched globally in 2018?", choices: ["Vine", "TikTok", "Snapchat", "Triller"], correctIndex: 1 },
    { key: "pc2", question: "Who is known as the 'Queen of Pop'?", choices: ["Beyoncé", "Madonna", "Lady Gaga", "Britney Spears"], correctIndex: 1 },
    { key: "pc3", question: "What color dress caused a viral internet debate in 2015?", choices: ["Blue and black / white and gold", "Red and green", "Purple and pink", "Yellow and white"], correctIndex: 0 },
    { key: "pc4", question: "Which billionaire acquired Twitter in 2022?", choices: ["Jeff Bezos", "Elon Musk", "Mark Zuckerberg", "Bill Gates"], correctIndex: 1 },
    { key: "pc5", question: "What meme features a Shiba Inu with colorful text?", choices: ["Grumpy Cat", "Doge", "Nyan Cat", "Pepe"], correctIndex: 1 },
    { key: "pc6", question: "Which reality TV family is famous for the show 'Keeping Up With...'?", choices: ["The Hiltons", "The Osbournes", "The Kardashians", "The Jenners"], correctIndex: 2 },
    { key: "pc7", question: "What year did the first iPhone launch?", choices: ["2005", "2007", "2009", "2010"], correctIndex: 1 },
    { key: "pc8", question: "Who slapped Chris Rock at the 2022 Oscars?", choices: ["Denzel Washington", "Will Smith", "Jamie Foxx", "Kevin Hart"], correctIndex: 1 },
    { key: "pc9", question: "What word did Merriam-Webster name Word of the Year in 2023?", choices: ["Authentic", "Rizz", "Vibe", "Gaslighting"], correctIndex: 0 },
    { key: "pc10", question: "Which streamer became the first to reach 100 million followers on TikTok?", choices: ["Addison Rae", "Khaby Lame", "Charli D'Amelio", "MrBeast"], correctIndex: 2 },
    { key: "pc11", question: "What is the name of Beyoncé's fanbase?", choices: ["Beliebers", "Swifties", "The BeyHive", "Little Monsters"], correctIndex: 2 },
    { key: "pc12", question: "Which social platform did Vine turn into (spiritually)?", choices: ["Instagram Reels", "TikTok", "YouTube Shorts", "Snapchat Spotlight"], correctIndex: 1 },
    { key: "pc13", question: "Who is the most-followed person on Instagram (as of 2024)?", choices: ["Kylie Jenner", "Lionel Messi", "Cristiano Ronaldo", "Selena Gomez"], correctIndex: 2 },
    { key: "pc14", question: "What year did TikTok surpass 1 billion users?", choices: ["2019", "2020", "2021", "2022"], correctIndex: 2 },
    { key: "pc15", question: "Which company owns Instagram?", choices: ["Google", "Meta", "Microsoft", "ByteDance"], correctIndex: 1 },
    { key: "pc16", question: "What is the name of MrBeast's chocolate bar brand?", choices: ["Feastables", "Beast Bites", "Jimmy's", "MrChoc"], correctIndex: 0 },
    { key: "pc17", question: "Which viral 2023 movie was paired with 'Oppenheimer' in 'Barbenheimer'?", choices: ["Barbie", "Poor Things", "Wonka", "Elemental"], correctIndex: 0 },
    { key: "pc18", question: "What slang term means 'charisma' from Gen Z internet culture?", choices: ["Sus", "Rizz", "Slay", "Bet"], correctIndex: 1 },
    { key: "pc19", question: "Who was TIME Person of the Year 2023?", choices: ["Elon Musk", "Taylor Swift", "Volodymyr Zelenskyy", "Sam Altman"], correctIndex: 1 },
    { key: "pc20", question: "Which game show revival did Ryan Seacrest take over hosting in 2024?", choices: ["Jeopardy!", "Wheel of Fortune", "The Price is Right", "Family Feud"], correctIndex: 1 },
    { key: "pc21", question: "What year was Facebook founded?", choices: ["2002", "2003", "2004", "2005"], correctIndex: 2 },
  ],
  Movies: [
    { key: "mv1", question: "Who directed the 1994 film Pulp Fiction?", choices: ["Martin Scorsese", "Quentin Tarantino", "Christopher Nolan", "Spike Lee"], correctIndex: 1 },
    { key: "mv2", question: "Which film won Best Picture at the 2020 Oscars?", choices: ["1917", "Joker", "Parasite", "Once Upon a Time in Hollywood"], correctIndex: 2 },
    { key: "mv3", question: "Who plays Iron Man in the MCU?", choices: ["Chris Evans", "Robert Downey Jr.", "Mark Ruffalo", "Chris Hemsworth"], correctIndex: 1 },
    { key: "mv4", question: "What is the highest-grossing film of all time (unadjusted)?", choices: ["Avatar", "Avengers: Endgame", "Titanic", "Star Wars: The Force Awakens"], correctIndex: 0 },
    { key: "mv5", question: "In The Godfather, what is the family's last name?", choices: ["Tattaglia", "Barzini", "Corleone", "Cuneo"], correctIndex: 2 },
    { key: "mv6", question: "Who directed Inception and Interstellar?", choices: ["Denis Villeneuve", "Christopher Nolan", "Ridley Scott", "Steven Spielberg"], correctIndex: 1 },
    { key: "mv7", question: "What is the name of the wizarding school in Harry Potter?", choices: ["Ilvermorny", "Beauxbatons", "Durmstrang", "Hogwarts"], correctIndex: 3 },
    { key: "mv8", question: "Which animated film features the song 'Let It Go'?", choices: ["Moana", "Tangled", "Frozen", "Encanto"], correctIndex: 2 },
    { key: "mv9", question: "Who directed Jaws (1975)?", choices: ["George Lucas", "Francis Ford Coppola", "Steven Spielberg", "Brian De Palma"], correctIndex: 2 },
    { key: "mv10", question: "In The Matrix, what color pill does Neo take?", choices: ["Blue", "Red", "Green", "Yellow"], correctIndex: 1 },
    { key: "mv11", question: "Which film features the quote 'I'll be back'?", choices: ["Predator", "The Terminator", "Total Recall", "Commando"], correctIndex: 1 },
    { key: "mv12", question: "Who directed the 2023 film Oppenheimer?", choices: ["Denis Villeneuve", "Christopher Nolan", "Greta Gerwig", "Martin Scorsese"], correctIndex: 1 },
    { key: "mv13", question: "Which actor played the Joker in The Dark Knight (2008)?", choices: ["Jared Leto", "Joaquin Phoenix", "Heath Ledger", "Jack Nicholson"], correctIndex: 2 },
    { key: "mv14", question: "What is the first Pixar feature film?", choices: ["A Bug's Life", "Toy Story", "Monsters Inc", "Finding Nemo"], correctIndex: 1 },
    { key: "mv15", question: "Which film features the character Forrest Gump?", choices: ["Cast Away", "Forrest Gump", "The Green Mile", "Big"], correctIndex: 1 },
    { key: "mv16", question: "Who directed Parasite (2019)?", choices: ["Park Chan-wook", "Bong Joon-ho", "Hirokazu Kore-eda", "Kim Jee-woon"], correctIndex: 1 },
    { key: "mv17", question: "What year was the first Star Wars film released?", choices: ["1975", "1977", "1979", "1980"], correctIndex: 1 },
    { key: "mv18", question: "Which actor voiced Woody in Toy Story?", choices: ["Tim Allen", "Tom Hanks", "Billy Crystal", "John Ratzenberger"], correctIndex: 1 },
    { key: "mv19", question: "Who directed Dune (2021)?", choices: ["Ridley Scott", "Denis Villeneuve", "David Lynch", "James Cameron"], correctIndex: 1 },
    { key: "mv20", question: "In Titanic (1997), what is the name of the diamond?", choices: ["Ocean's Tear", "Heart of the Sea", "Heart of the Ocean", "Blue Diamond"], correctIndex: 2 },
    { key: "mv21", question: "Which movie won Best Picture at the 2024 Oscars?", choices: ["Barbie", "Killers of the Flower Moon", "Oppenheimer", "Poor Things"], correctIndex: 2 },
  ],
  TV: [
    { key: "tv1", question: "In Breaking Bad, what is Walter White's chemistry teacher alias?", choices: ["Heisenberg", "Schrader", "Pinkman", "Mr. White"], correctIndex: 0 },
    { key: "tv2", question: "What is the name of the coffee shop in Friends?", choices: ["Central Perk", "Java Joe's", "The Grind", "Perk Up"], correctIndex: 0 },
    { key: "tv3", question: "In Game of Thrones, who kills the Night King?", choices: ["Jon Snow", "Daenerys", "Arya Stark", "Bran"], correctIndex: 2 },
    { key: "tv4", question: "Which Netflix show features the Upside Down?", choices: ["Dark", "Stranger Things", "The OA", "Wednesday"], correctIndex: 1 },
    { key: "tv5", question: "In The Office (US), what is the name of the paper company?", choices: ["Staples", "Dunder Mifflin", "Michael Scott Paper", "Sabre"], correctIndex: 1 },
    { key: "tv6", question: "Who is the main character of Better Call Saul?", choices: ["Walter White", "Jimmy McGill", "Mike Ehrmantraut", "Gus Fring"], correctIndex: 1 },
    { key: "tv7", question: "What HBO show is based on the Westeros continent?", choices: ["Rome", "House of the Dragon", "The Last of Us", "Succession"], correctIndex: 1 },
    { key: "tv8", question: "In Squid Game, what is the prize money in Korean won (approx)?", choices: ["4.56 billion", "45.6 billion", "456 million", "45.6 million"], correctIndex: 1 },
    { key: "tv9", question: "Which sitcom features Sheldon Cooper?", choices: ["How I Met Your Mother", "The Big Bang Theory", "Community", "Modern Family"], correctIndex: 1 },
    { key: "tv10", question: "What is the longest-running American animated sitcom?", choices: ["Family Guy", "South Park", "The Simpsons", "American Dad"], correctIndex: 2 },
    { key: "tv11", question: "In Ted Lasso, what team does Ted coach?", choices: ["AFC Richmond", "West Ham", "Manchester City", "Chelsea"], correctIndex: 0 },
    { key: "tv12", question: "In The Mandalorian, what is Grogu's popular nickname?", choices: ["Baby Groot", "Baby Yoda", "Little Jedi", "Yodito"], correctIndex: 1 },
    { key: "tv13", question: "What show features the character Eleven with psychic powers?", choices: ["Wednesday", "The Umbrella Academy", "Stranger Things", "Locke & Key"], correctIndex: 2 },
    { key: "tv14", question: "In Succession, what company do the Roys run?", choices: ["Waystar Royco", "GoJo", "PGM", "Pierce"], correctIndex: 0 },
    { key: "tv15", question: "Who created Rick and Morty?", choices: ["Seth MacFarlane", "Dan Harmon & Justin Roiland", "Matt Groening", "Trey Parker"], correctIndex: 1 },
    { key: "tv16", question: "In The Last of Us, who plays Joel?", choices: ["Pedro Pascal", "Oscar Isaac", "Nikolaj Coster-Waldau", "Kit Harington"], correctIndex: 0 },
    { key: "tv17", question: "What is the name of Sherlock Holmes' apartment address?", choices: ["221A Baker St", "221B Baker St", "121B Baker St", "222B Baker St"], correctIndex: 1 },
    { key: "tv18", question: "Which Star Trek captain says 'Make it so'?", choices: ["Kirk", "Picard", "Sisko", "Janeway"], correctIndex: 1 },
    { key: "tv19", question: "What series follows the Peaky Blinders gang?", choices: ["Boardwalk Empire", "Peaky Blinders", "Ozark", "Sons of Anarchy"], correctIndex: 1 },
    { key: "tv20", question: "In Avatar: The Last Airbender, what nation is Aang from?", choices: ["Water Tribe", "Fire Nation", "Air Nomads", "Earth Kingdom"], correctIndex: 2 },
    { key: "tv21", question: "Who is the drug kingpin in Narcos season 1?", choices: ["Amado Carrillo", "Pablo Escobar", "El Chapo", "Cali Cartel"], correctIndex: 1 },
  ],
  Music: [
    { key: "ms1", question: "Which band released the album 'Abbey Road' in 1969?", choices: ["The Rolling Stones", "The Beatles", "Led Zeppelin", "The Who"], correctIndex: 1 },
    { key: "ms2", question: "Who is known as the 'King of Pop'?", choices: ["Elvis Presley", "Michael Jackson", "Prince", "Justin Timberlake"], correctIndex: 1 },
    { key: "ms3", question: "How many Grammy Awards has Beyoncé won (most all-time as of 2024)?", choices: ["28", "32", "35", "40"], correctIndex: 1 },
    { key: "ms4", question: "Which Taylor Swift album was released in 2022?", choices: ["Folklore", "Evermore", "Midnights", "Lover"], correctIndex: 2 },
    { key: "ms5", question: "Who sang 'Bohemian Rhapsody'?", choices: ["Led Zeppelin", "Queen", "The Who", "Pink Floyd"], correctIndex: 1 },
    { key: "ms6", question: "What is BTS's fandom called?", choices: ["ARMY", "BLINK", "ONCE", "STAY"], correctIndex: 0 },
    { key: "ms7", question: "Which rapper released 'good kid, m.A.A.d city'?", choices: ["Drake", "J. Cole", "Kendrick Lamar", "Kanye West"], correctIndex: 2 },
    { key: "ms8", question: "Who produced the album 'Thriller' with Michael Jackson?", choices: ["Rick Rubin", "Quincy Jones", "Dr. Dre", "Timbaland"], correctIndex: 1 },
    { key: "ms9", question: "What instrument is Yo-Yo Ma famous for?", choices: ["Violin", "Piano", "Cello", "Flute"], correctIndex: 2 },
    { key: "ms10", question: "Which artist headlined the 2023 Super Bowl halftime show?", choices: ["The Weeknd", "Rihanna", "Dr. Dre", "Usher"], correctIndex: 1 },
    { key: "ms11", question: "What genre is Bad Bunny best known for?", choices: ["K-pop", "Reggaeton", "Country", "EDM"], correctIndex: 1 },
    { key: "ms12", question: "Which artist released 'Renaissance' in 2022?", choices: ["Rihanna", "Beyoncé", "Adele", "SZA"], correctIndex: 1 },
    { key: "ms13", question: "Who is the lead vocalist of Coldplay?", choices: ["Chris Martin", "Jonny Buckland", "Guy Berryman", "Will Champion"], correctIndex: 0 },
    { key: "ms14", question: "Which K-pop group has members Jennie, Lisa, Rosé, and Jisoo?", choices: ["TWICE", "BLACKPINK", "Red Velvet", "ITZY"], correctIndex: 1 },
    { key: "ms15", question: "What was Nirvana's breakthrough 1991 album?", choices: ["In Utero", "Bleach", "Nevermind", "Incesticide"], correctIndex: 2 },
    { key: "ms16", question: "Which DJ produced 'Wake Me Up'?", choices: ["Calvin Harris", "Avicii", "Zedd", "David Guetta"], correctIndex: 1 },
    { key: "ms17", question: "What is Drake's home city?", choices: ["Atlanta", "Toronto", "Los Angeles", "New York"], correctIndex: 1 },
    { key: "ms18", question: "Which artist is known for the album 'Lemonade'?", choices: ["Beyoncé", "Rihanna", "Alicia Keys", "Solange"], correctIndex: 0 },
    { key: "ms19", question: "Who wrote 'Blowin' in the Wind'?", choices: ["Bob Dylan", "Joni Mitchell", "Neil Young", "Simon & Garfunkel"], correctIndex: 0 },
    { key: "ms20", question: "What band recorded 'Dark Side of the Moon'?", choices: ["Led Zeppelin", "Pink Floyd", "The Who", "Deep Purple"], correctIndex: 1 },
    { key: "ms21", question: "Which rapper's real name is Aubrey Graham?", choices: ["Drake", "The Weeknd", "Travis Scott", "J. Cole"], correctIndex: 0 },
  ],
};

function toQuestion(m: Omit<Mock, "category">, category: string, i: number): Question {
  return {
    id: `mock-${category}-${m.key}`,
    quizNumber: 0,
    order: i,
    question: m.question,
    choices: m.choices,
    correctIndex: m.correctIndex,
    category,
  };
}

export function getMockPool(category: string | null): Question[] {
  if (!category || category === "All Fandoms") {
    return Object.entries(raw).flatMap(([cat, items]) =>
      items.map((m, i) => toQuestion(m, cat, i)),
    );
  }
  const items = raw[category];
  if (!items) return [];
  return items.map((m, i) => toQuestion(m, category, i));
}