/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as MyQuestsRouteImport } from './routes/my-quests'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DoubtSolverIndexRouteImport } from './routes/doubt-solver.index'
import { Route as DoubtSolverThreadIdRouteImport } from './routes/doubt-solver.$threadId'
import { Route as ApiDoubtChatRouteImport } from './routes/api/doubt-chat'

const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const MyQuestsRoute = MyQuestsRouteImport.update({
  id: '/my-quests',
  path: '/my-quests',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DoubtSolverIndexRoute = DoubtSolverIndexRouteImport.update({
  id: '/doubt-solver/',
  path: '/doubt-solver/',
  getParentRoute: () => rootRouteImport,
} as any)
const DoubtSolverThreadIdRoute = DoubtSolverThreadIdRouteImport.update({
  id: '/doubt-solver/$threadId',
  path: '/doubt-solver/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDoubtChatRoute = ApiDoubtChatRouteImport.update({
  id: '/api/doubt-chat',
  path: '/api/doubt-chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/leaderboard': typeof LeaderboardRoute
  '/my-quests': typeof MyQuestsRoute
  '/practice': typeof PracticeRoute
  '/quiz': typeof QuizRoute
  '/results': typeof ResultsRoute
  '/api/doubt-chat': typeof ApiDoubtChatRoute
  '/doubt-solver/$threadId': typeof DoubtSolverThreadIdRoute
  '/doubt-solver/': typeof DoubtSolverIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/leaderboard': typeof LeaderboardRoute
  '/my-quests': typeof MyQuestsRoute
  '/practice': typeof PracticeRoute
  '/quiz': typeof QuizRoute
  '/results': typeof ResultsRoute
  '/api/doubt-chat': typeof ApiDoubtChatRoute
  '/doubt-solver/$threadId': typeof DoubtSolverThreadIdRoute
  '/doubt-solver': typeof DoubtSolverIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/leaderboard': typeof LeaderboardRoute
  '/my-quests': typeof MyQuestsRoute
  '/practice': typeof PracticeRoute
  '/quiz': typeof QuizRoute
  '/results': typeof ResultsRoute
  '/api/doubt-chat': typeof ApiDoubtChatRoute
  '/doubt-solver/$threadId': typeof DoubtSolverThreadIdRoute
  '/doubt-solver/': typeof DoubtSolverIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/leaderboard'
    | '/my-quests'
    | '/practice'
    | '/quiz'
    | '/results'
    | '/api/doubt-chat'
    | '/doubt-solver/$threadId'
    | '/doubt-solver/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/leaderboard'
    | '/my-quests'
    | '/practice'
    | '/quiz'
    | '/results'
    | '/api/doubt-chat'
    | '/doubt-solver/$threadId'
    | '/doubt-solver'
  id:
    | '__root__'
    | '/'
    | '/leaderboard'
    | '/my-quests'
    | '/practice'
    | '/quiz'
    | '/results'
    | '/api/doubt-chat'
    | '/doubt-solver/$threadId'
    | '/doubt-solver/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LeaderboardRoute: typeof LeaderboardRoute
  MyQuestsRoute: typeof MyQuestsRoute
  PracticeRoute: typeof PracticeRoute
  QuizRoute: typeof QuizRoute
  ResultsRoute: typeof ResultsRoute
  ApiDoubtChatRoute: typeof ApiDoubtChatRoute
  DoubtSolverThreadIdRoute: typeof DoubtSolverThreadIdRoute
  DoubtSolverIndexRoute: typeof DoubtSolverIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-quests': {
      id: '/my-quests'
      path: '/my-quests'
      fullPath: '/my-quests'
      preLoaderRoute: typeof MyQuestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doubt-solver/': {
      id: '/doubt-solver/'
      path: '/doubt-solver'
      fullPath: '/doubt-solver/'
      preLoaderRoute: typeof DoubtSolverIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doubt-solver/$threadId': {
      id: '/doubt-solver/$threadId'
      path: '/doubt-solver/$threadId'
      fullPath: '/doubt-solver/$threadId'
      preLoaderRoute: typeof DoubtSolverThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/doubt-chat': {
      id: '/api/doubt-chat'
      path: '/api/doubt-chat'
      fullPath: '/api/doubt-chat'
      preLoaderRoute: typeof ApiDoubtChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LeaderboardRoute: LeaderboardRoute,
  MyQuestsRoute: MyQuestsRoute,
  PracticeRoute: PracticeRoute,
  QuizRoute: QuizRoute,
  ResultsRoute: ResultsRoute,
  ApiDoubtChatRoute: ApiDoubtChatRoute,
  DoubtSolverThreadIdRoute: DoubtSolverThreadIdRoute,
  DoubtSolverIndexRoute: DoubtSolverIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
